CUDA_VISIBLE_DEVICES=2 python3 batch_inference.py --model_path log_5x5_dublin_1/epoch_49.ckpt --dump_dir log_5x5_dublin_1/dump_withNonBuilding_RGBFormat --output_filelist log_5x5_dublin_1/output_filelist.txt --room_data_filelist meta/area1_data_label_dublin.txt --area 1 --visu --jenis dublin
CUDA_VISIBLE_DEVICES=2 python3 batch_inference.py --model_path log_5x5_dublin_2/epoch_49.ckpt --dump_dir log_5x5_dublin_2/dump_withNonBuilding_RGBFormat --output_filelist log_5x5_dublin_2/output_filelist.txt --room_data_filelist meta/area2_data_label_dublin.txt --area 2 --visu --jenis dublin
CUDA_VISIBLE_DEVICES=2 python3 batch_inference.py --model_path log_5x5_dublin_3/epoch_49.ckpt --dump_dir log_5x5_dublin_3/dump_withNonBuilding_RGBFormat --output_filelist log_5x5_dublin_3/output_filelist.txt --room_data_filelist meta/area3_data_label_dublin.txt --area 3 --visu --jenis dublin
CUDA_VISIBLE_DEVICES=2 python3 batch_inference.py --model_path log_5x5_dublin_4/epoch_49.ckpt --dump_dir log_5x5_dublin_4/dump_withNonBuilding_RGBFormat --output_filelist log_5x5_dublin_4/output_filelist.txt --room_data_filelist meta/area4_data_label_dublin.txt --area 4 --visu --jenis dublin
CUDA_VISIBLE_DEVICES=2 python3 batch_inference.py --model_path log_5x5_dublin_5/epoch_49.ckpt --dump_dir log_5x5_dublin_5/dump_withNonBuilding_RGBFormat --output_filelist log_5x5_dublin_5/output_filelist.txt --room_data_filelist meta/area5_data_label_dublin.txt --area 5 --visu --jenis dublin
CUDA_VISIBLE_DEVICES=2 python3 batch_inference.py --model_path log_5x5_dublin_6/epoch_49.ckpt --dump_dir log_5x5_dublin_6/dump_withNonBuilding_RGBFormat --output_filelist log_5x5_dublin_6/output_filelist.txt --room_data_filelist meta/area6_data_label_dublin.txt --area 6 --visu --jenis dublin

CUDA_VISIBLE_DEVICES=2 python3 batch_inference_build_only.py --model_path log_5x5_dublin_1/epoch_49.ckpt --dump_dir log_5x5_dublin_1/dump_RGBFormat --output_filelist log_5x5_dublin_1/output_filelist.txt --room_data_filelist meta/area1_data_label_dublin.txt --area 1 --visu --jenis dublin
CUDA_VISIBLE_DEVICES=2 python3 batch_inference_build_only.py --model_path log_5x5_dublin_2/epoch_49.ckpt --dump_dir log_5x5_dublin_2/dump_RGBFormat --output_filelist log_5x5_dublin_2/output_filelist.txt --room_data_filelist meta/area2_data_label_dublin.txt --area 2 --visu --jenis dublin
CUDA_VISIBLE_DEVICES=2 python3 batch_inference_build_only.py --model_path log_5x5_dublin_3/epoch_49.ckpt --dump_dir log_5x5_dublin_3/dump_RGBFormat --output_filelist log_5x5_dublin_3/output_filelist.txt --room_data_filelist meta/area3_data_label_dublin.txt --area 3 --visu --jenis dublin
CUDA_VISIBLE_DEVICES=2 python3 batch_inference_build_only.py --model_path log_5x5_dublin_4/epoch_49.ckpt --dump_dir log_5x5_dublin_4/dump_RGBFormat --output_filelist log_5x5_dublin_4/output_filelist.txt --room_data_filelist meta/area4_data_label_dublin.txt --area 4 --visu --jenis dublin
CUDA_VISIBLE_DEVICES=2 python3 batch_inference_build_only.py --model_path log_5x5_dublin_5/epoch_49.ckpt --dump_dir log_5x5_dublin_5/dump_RGBFormat --output_filelist log_5x5_dublin_5/output_filelist.txt --room_data_filelist meta/area5_data_label_dublin.txt --area 5 --visu --jenis dublin
CUDA_VISIBLE_DEVICES=2 python3 batch_inference_build_only.py --model_path log_5x5_dublin_6/epoch_49.ckpt --dump_dir log_5x5_dublin_6/dump_RGBFormat --output_filelist log_5x5_dublin_6/output_filelist.txt --room_data_filelist meta/area6_data_label_dublin.txt --area 6 --visu --jenis dublin